package comune.tivoli.rm.it.ComuneTivoli.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notizieSitoDbSqlLiteDaoConfig;

    private final NotizieSitoDbSqlLiteDao notizieSitoDbSqlLiteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notizieSitoDbSqlLiteDaoConfig = daoConfigMap.get(NotizieSitoDbSqlLiteDao.class).clone();
        notizieSitoDbSqlLiteDaoConfig.initIdentityScope(type);

        notizieSitoDbSqlLiteDao = new NotizieSitoDbSqlLiteDao(notizieSitoDbSqlLiteDaoConfig, this);

        registerDao(NotizieSitoDbSqlLite.class, notizieSitoDbSqlLiteDao);
    }
    
    public void clear() {
        notizieSitoDbSqlLiteDaoConfig.getIdentityScope().clear();
    }

    public NotizieSitoDbSqlLiteDao getNotizieSitoDbSqlLiteDao() {
        return notizieSitoDbSqlLiteDao;
    }

}
