package comune.tivoli.rm.it.ComuneTivoli.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTIZIE_SITO_DB_SQL_LITE.
 */
public class NotizieSitoDbSqlLite {

    private Long id;
    /** Not-null value. */
    private java.util.Date dataInserimento;
    /** Not-null value. */
    private java.util.Date data;
    /** Not-null value. */
    private String titolo;
    /** Not-null value. */
    private String testo;
    /** Not-null value. */
    private String html;
    private long token;
    /** Not-null value. */
    private String url;
    private boolean flagContenutoLetto;
    /** Not-null value. */
    private String key;

    public NotizieSitoDbSqlLite() {
    }

    public NotizieSitoDbSqlLite(Long id) {
        this.id = id;
    }

    public NotizieSitoDbSqlLite(Long id, java.util.Date dataInserimento, java.util.Date data, String titolo, String testo, String html, long token, String url, boolean flagContenutoLetto, String key) {
        this.id = id;
        this.dataInserimento = dataInserimento;
        this.data = data;
        this.titolo = titolo;
        this.testo = testo;
        this.html = html;
        this.token = token;
        this.url = url;
        this.flagContenutoLetto = flagContenutoLetto;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getDataInserimento() {
        return dataInserimento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDataInserimento(java.util.Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    /** Not-null value. */
    public java.util.Date getData() {
        return data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData(java.util.Date data) {
        this.data = data;
    }

    /** Not-null value. */
    public String getTitolo() {
        return titolo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    /** Not-null value. */
    public String getTesto() {
        return testo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTesto(String testo) {
        this.testo = testo;
    }

    /** Not-null value. */
    public String getHtml() {
        return html;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHtml(String html) {
        this.html = html;
    }

    public long getToken() {
        return token;
    }

    public void setToken(long token) {
        this.token = token;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public boolean getFlagContenutoLetto() {
        return flagContenutoLetto;
    }

    public void setFlagContenutoLetto(boolean flagContenutoLetto) {
        this.flagContenutoLetto = flagContenutoLetto;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

}
